
[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 3, y = 3 }
opacity = 0.97

[font]
size = 12
normal = { family = "RobotoMono Nerd Font", style = "Regular" } 

[general]
import = [
  "~/.config/alacritty/tokyonight_night.toml"
]
