[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 3, y = 3 }
opacity = 1

[font]
size = 12
normal = { family = "FiraCode Nerd Font", style = "Regular" } 
bold = { family = "FiraCode Nerd Font", style = "Bold" } 
italic = { family = "VictorMono Nerd Font", style = "Italic" } 
bold_italic = { family = "VictorMono Nerd Font", style = "Bold Italic" } 

[general]
import = [
  "~/.config/alacritty/tokyonight_night.toml"
]
