
[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 3, y = 3 }

[font]
size = 12
normal = { family = "RobotoMono Nerd Font", style = "Regular" } 

[general]
import = [
#"~/.config/alacritty/rose-pine-moon.toml"
"~/.config/alacritty/catppuccin-macchiato.toml"
]
