# Sets user-defined palette
palette = "rose_pine_moon"

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_state\
$git_status
$jobs\
$battery\
$character
"""

[palettes.rose_pine_moon]
red = "#eb6f92"
yellow = "#f6c177"
green = "#9ccfd8"
blue = "#3e8fb0"
rose = "#ea9a97"
purple = "#c4a7e7"
white = "#e0def4"
#black = ""
#cyan = ""
#orange = ""

[directory]
truncation_length = 4
style = "bold white"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
